### PR TITLE
fix typo ("a", not "an")

### PR DESCRIPTION
**Pull request by tacman**

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
This is a read-only subtree split isn't it?

**Comment by tacman** [comment]
probably.  I often have trouble finding the source to make the change.  Since that's an automated process, could you add a link to where it is in the monorepo?  Since the main code, UX and documentation are separate repos, sometimes it's a bit of a challenge to figure out where to suggest a change or post an issue.

**Comment by Kocal** [comment]
It is supposed to be read-only yes... 🤔 

I will ping Fabien about that

**Comment by Kocal** [comment]
Yes, I want to do something like that https://github.com/symfony/http-client/pull/13#issuecomment-1275101434

@nicolas-grekas any hints? 🙏🏻 :)

**Comment by Kocal** [comment]
Opened https://github.com/symfony/ux/pull/2395, this should fix the problem and makes UX packages splits read-only.

@tacman can you open your PR on symfony/ux instead please? Thanks 🙏🏻

**Pull request closed without merging**
